### ISSUE TITLE
TypeError in context

### ISSUE THREAD

**Issue by hdamron17** [jyn514/GrepMe#32]
If context goes out of the bounds of a chat (or possibly if there is a failed request where context should be), there is an exception where the message becomes NoneType and breaks. See following stack trace for `grepme -g "Oak Pointe Elementary STEM Night" -A10 "~5"` (I chose this chat because it is not likely to change much and it seems to only break on context after):
```
--- Oak Pointe Elementary STEM Night ---
Joshua Nelson: We're making a u turn, we'll be there in ~5 minutes
Samyu Comandur: where are y’all
Samyu Comandur: @Nathan Kilcoyne
Samyu Comandur: Traceback (most recent call last):
  File "/usr/local/opt/pyenv/versions/3.7.3/bin/grepme", line 10, in <module>
    sys.exit(main())
  File "/usr/local/opt/pyenv/versions/3.7.3/Python.framework/Versions/3.7/lib/python3.7/site-packages/grepme/__main__.py", line 38, in main
    search_all(config)
  File "/usr/local/opt/pyenv/versions/3.7.3/Python.framework/Versions/3.7/lib/python3.7/site-packages/grepme/lib.py", line 300, in search_all
    print_message(buffer, i, args)
  File "/usr/local/opt/pyenv/versions/3.7.3/Python.framework/Versions/3.7/lib/python3.7/site-packages/grepme/lib.py", line 188, in print_message
    add_attachments(message)
  File "/usr/local/opt/pyenv/versions/3.7.3/Python.framework/Versions/3.7/lib/python3.7/site-packages/grepme/lib.py", line 46, in add_attachments
    message['text'] += '\n'
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
```

**Comment by jyn514** [comment]
This is because of a message that has only a picture and no text. It was fixed in grepme 1.3.1, can you confirm whether you have a lower version installed? (`grepme -V`)

**Comment by hdamron17** [comment]
I am using Grepme 1.3.1 - it is on Mac not Linux if that makes a difference. I am also using Python 3.7.3 so it shouldn't be outdated.

**Comment by hdamron17** [comment]
If I get a chance, I'll dig deeper into the issue. Possibly there are some tests I could run on my machine to ensure it's not a difference between Mac and Linux?

**Comment by hdamron17** [comment]
I ran the tests provided for CI and all pass.

**Comment by jyn514** [comment]
My bad, it was fixed in 1.4, not 1.3. Can you upgrade and see if it's still an issue?
